# Maintainer: Jonas Strassel <info@jonas-strassel.de>
# Description: Builds multi-arch docker images to be used in ci-environments

name: image_build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '30 2 * * 0'

env: 
  PACMAN_VERSION: 5.2.2
  ARCH_INSTALL_SCRIPTS_VERSION: 23
  DOCKER_ORGANIZATION: manjarosway
  PLATFORMS: linux/arm64,linux/amd64

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - 
        name: checkout
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      -
        name: prepare
        run: |
          echo "DATE=$(date +%Y%m%d)" >>$GITHUB_ENV
      -
        name: download-amd64-rootfs
        run: |
          curl -s https://api.github.com/repos/Manjaro-Sway/manjaro-rootfs-x86_64/releases/latest \
            | grep browser_download_url \
            | grep manjaro_rootfs_x86_64.tar \
            | cut -d '"' -f 4 \
            | wget -O linux/amd64.tar -qi -
      - 
        name: download-arm64-rootfs
        run: wget -O linux/arm64.tar -q https://osdn.net/projects/manjaro-arm/storage/.rootfs/Manjaro-ARM-aarch64-latest.tar.gz
      -
        name: setup-qemu
        uses: docker/setup-qemu-action@v1
      -
        name: setup-buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.3.0
      -
        name: login-docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: build-push-docker-base
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            CACHEBUST=${{ env.DATE }}
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: manjarosway/base:${{ env.DATE }},manjarosway/base:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: move-cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache